### ISSUE TITLE
Still Japanese

### ISSUE THREAD

**Issue by MediaMaquina** [concreted/dqiv-nds-en-script-patcher#1]
I followed all steps. The game is still in Japanese.
I don't know what else to do.

**Comment by concreted** [comment]
If you followed the steps in `Quick Start`, you will have a ROM that will still display Japanese text by default, unless you use an Action Replay code to set the ROM's language mode to English:

> You have now generated a JA ROM with patched English script which includes party chat. This ROM will still use Japanese text by default, but can be switched to English with the Action Replay code `02106404 00000001`.

If you don't want to use an Action Replay code and want the ROM to display English by default, try these steps:

> Alternatively, you can run `python dqiv_patch.py --lang ja` to generate a ja output folder. Copy this to the `<dslazy_directory>/NDS_UNPACK/data/data/mess` directory, replacing the `ja` folder, and pack the ROM is dslazy. This ROM will show the English script without requiring an Action Replay code.

**Comment by MediaMaquina** [comment]
Working beautifully thanks.
names cannot be entered using English alphabet am i right?

**Comment by concreted** [comment]
Great! Yes unfortunately the Japan ROM doesn't seem to support entering English names, even in English language mode. If someone finds a way to patch the ROM to support that, I would like to add it to this tool.

**Comment by MediaMaquina** [comment]
Thanks so much you are a legend!
