### ISSUE TITLE
"ja" mode rom will have "en" mode formatting if action replay code is used

### ISSUE THREAD

**Issue by MediaMaquina** [concreted/dqiv-nds-en-script-patcher#2]
So i was fiddling with this trying to make a rom that will be both:

1) English by Default.
2) Have English formatting (names above).

And i realized that if i use a "--lang ja" rom + action replay code 02106404 00000001 i get exactly that.

Am i insane or that just works and was stated and i didn't get it. (again)

**Comment by concreted** [comment]
What this sounds like is you have a ROM that you previously added the `en` folder generated from `dqiv_patch.py` (which is equivalent to running with `--lang en`). Such a ROM would:
1. Display Japanese text by default
2. With Action Replay code, display English text with names above.

If you then added the `ja` folder generated by `--lang ja` to this ROM, you would get a ROM that:
1. By default, i.e. without any Action Replay code, displays English with names inline with text 
2. With Action Replay code, displays English with names above

Does this make sense? Basically, the ROM will default to using the `ja` folder inside the ROM. The AR code is to make it use the `en` folder instead.

**Comment by concreted** [comment]
Closing this issue, but feel free to reply here or open a new issue if you have any more questions
