### ISSUE TITLE
Torneko Appraise 

### ISSUE THREAD

**Issue by Ditogalaxy** [concreted/dqiv-nds-en-script-patcher#3]
Minor issue but I got to ch3 and the menu text for Torneko's appraise is still in Japanese, though you can click on it as usual and the actual appraisal is in english. don't know if you've noticed. 
 
![image](https://user-images.githubusercontent.com/86443532/123333581-2b1cf880-d4ff-11eb-927a-8d96a19a265f.png)

**Comment by concreted** [comment]
Yes I've noticed this in chapter 3 as well, this its the same issue noted in the "Known issues" section of the readme: 

```
The map screen shows "Map Info" and other strings showing shop info in Japanese. Although the "Map Info" string is present in the en script files, the JA ROM seems to be hardcoded to show this string in Japanese. Replacing the corresponding file in the ja folder doesn't help. A few other strings are also affected in inventory screens, may be others I haven't found.
```

Unfortunately this doesn't appear to be fixable without tweaking the game code, which is out of scope of what this tool does.
